development:
  cloud_name: <%= Figaro.env.cloudinary_cloud_name %>
  api_key: <%= Figaro.env.cloudinary_api_key %>
  api_secret: <%= Figaro.env.cloudinary_api_secret %>
  enhance_image_tag: true
  static_image_support: false
  secure: true

production:
  cloud_name: <%= Figaro.env.cloudinary_cloud_name %>
  api_key: <%= Figaro.env.cloudinary_api_key %>
  api_secret: <%= Figaro.env.cloudinary_api_secret %>
  enhance_image_tag: true
  static_image_support: true
  secure: true

test:
  cloud_name: <%= Figaro.env.cloudinary_cloud_name %>
  api_key: <%= Figaro.env.cloudinary_api_key %>
  api_secret: <%= Figaro.env.cloudinary_api_secret %>
  enhance_image_tag: true
  static_image_support: false
  secure: true
